name: 'carmen_sandiego'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project
profile: 'carmen_sandiego'

# These configurations specify where dbt should look for different types of files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  carmen_sandiego:
    # Staging layer: Views for fast development and always-fresh data
    staging:
      +materialized: view
      +schema: staging
      +docs:
        node_color: "#90EE90"
        
    # Intermediate layer: Views for transformation logic
    intermediate:
      +materialized: view
      +schema: intermediate
      +docs:
        node_color: "#FFE4B5"
        
    # Marts layer: Production-ready data models
    marts:
      +schema: marts
      +docs:
        node_color: "#87CEEB"
        
      # Core: Dimensional model as tables for performance
      core:
        +materialized: table
        +schema: core
        
      # Analytics: Views per assessment requirements  
      analytics:
        +materialized: view
        +schema: analytics
      
# Seed configuration
seeds:
  carmen_sandiego:
    +quote_columns: true

# Global project variables
vars:
  # Date range for analysis
  start_date: '1990-01-01'
  end_date: '2025-12-31'
  
  # Assessment metadata
  assessment_date: '2025-07-14'
  
  # Business logic variables
  top_behaviors_limit: 3

# Require dbt version (ensures compatibility)
require-dbt-version: ">=1.0.0"